# default_platform(:android)
#
# platform :android do
#   desc "Build a debug APK for the dev flavor"
#   lane :beta do
#     gradle(task: "assembleDevDebug")
#   end
# end

default_platform(:android)

platform :android do
  desc "Bump the build number in pubspec.yaml"
  lane :bump_version do
    pubspec_path = File.expand_path("../../pubspec.yaml", __dir__)
    content = File.read(pubspec_path)

    content.match(/version:\s*(\d+\.\d+\.\d+)\+(\d+)/)
    version_name = $1
    build_number = $2.to_i
    new_build_number = build_number + 1

    new_content = content.sub(
      /version:\s*\d+\.\d+\.\d+\+\d+/,
      "version: #{version_name}+#{new_build_number}"
    )

    File.write(pubspec_path, new_content)
    UI.success("Bumped build number to #{new_build_number}")
  end

  desc "Build a debug APK for the dev flavor"
  lane :beta do
    bump_version
    gradle(task: "assembleDevDebug")
  end

  desc "Build a signed release APK for the dev flavor"
  lane :release do
    bump_version
    gradle(task: "assembleDevRelease")
  end
  desc "Build and distribute to Firebase App Distribution"
  lane :distribute do
    bump_version
    gradle(task: "assembleDevRelease")
    firebase_app_distribution(
      app: "1:657967720137:android:beb1a980d4cb015f580f18", # your dev Firebase App ID
      groups: "testers",
      release_notes: "Automated build from develop branch",
      service_credentials_file: "firebase-service-account.json"
      android_artifact_type: "APK",
      android_artifact_path: "app/build/outputs/apk/dev/release/app-dev-release.apk"
    )
  end
end